infer_eval_metric: True
detect_and_drop_id_column: False
task_preprocessors_timeout: 3600
save_artifacts:
  enabled: False
  append_timestamp: True
  path: "./aga-artifacts"
  # path: "s3://autogluon-assistant-agts/outputs/<run_id>/aga-artifacts/"
feature_transformers:
  # - _target_: autogluon_assistant.transformer.CAAFETransformer
  #   eval_model: lightgbm
  #   llm_model: gpt-3.5-turbo
  #   num_iterations: 2
  #   optimization_metric: roc
  # - _target_: autogluon_assistant.transformer.OpenFETransformer
  #   n_jobs: 1
  #   num_features_to_keep: 10
  #- _target_: autogluon_assistant.transformer.PretrainedEmbeddingTransformer
  #    model_name: 'all-mpnet-base-v2'
  - _target_: autogluon_assistant.transformer.SimpleGenTransformer
    n_jobs: 1
    llm_model: bedrock-claude-3.5-sonnet
autogluon:
  predictor_init_kwargs: {}
  predictor_fit_kwargs:
    verbosity: 2
    presets: best_quality
    time_limit: 14400
    dynamic_stacking: False
    num_stack_levels: 0
llm:
  # Note: bedrock is only supported in limited AWS regions
  provider: bedrock
  api_key_location: BEDROCK_API_KEY
  model: "anthropic.claude-3-5-sonnet-20240620-v1:0"
  # provider: openai
  # api_key_location: OPENAI_API_KEY
  # model: gpt-4o-2024-08-06
  # model: gpt-3.5-turbo
  max_tokens: 512
  proxy_url: null
  temperature: 0
  verbose: True